- api/co_v1/company.go
- api/co_v1/employee.go
- api/co_v1/team.go
- co_controller/company.go
- co_controller/employee.go
- co_controller/team.go
- co_model/company.go
- co_model/employee.go
- co_model/team.go
- go.mod
- go.sum
> fix：优化控制层bool类型转化一直true BUG

- internal/logic/company/company.go
- 不需要创建默认员工的时候，employee是不存在的，设置w为0即可
> fix: 修复创建公司Bug

- internal/logic/company/company_employee.go
> fix: 判断id的时候需要转换类型

- internal/logic/company/company_team.go
- ids之前没有赋值，ids应该是团队成员列表中的employeeIDs
- 还有items定义类型有误
> fix: 获取团队成员列表方法修复

- co_router/router.go
> pref: 优化团队小组的接口命名

- api/co_v1/employee.go
> fix: 设置员工手机号码接口命名错误

- co_consts/consts.go
> pref: 重置文件上传存储文件夹

- co_consts/consts.go
- co_interface/co_interface.go
- co_model/co_dao/company.go
- co_model/co_dao/company_employee.go
- co_model/co_dao/company_team.go
- co_model/co_dao/company_team_member.go
- co_model/co_dao/custom.go
- co_model/config.go
- co_module/modules.go
- example/main.go
- go.mod
- go.sum
- i18n/company/zh-CN.yaml
- internal/boot/boot.go
- internal/logic/company/company.go
- internal/logic/company/company_employee.go
- internal/logic/company/company_team.go
- internal/tpls/consts_gen_dao_template_dao.tpl
目前应用： 
-  错误提示信息有用到
优点：
- 不同的项目可以修改其yaml配置文件即可修改，例如 ：
- 员工 --> 会员，只需要修改一下配置文件中的EmployeeName即可
> feat: 添加i18n国际化对象的使用

- internal/logic/company/company_team.go
- 如果Team的队长没指定的话，那么这时候是不需要创建团队成员的
> pref: 优化创建团队的时候是否创建团队队长

- go.mod
- go.sum
- internal/logic/company/company.go
- internal/logic/company/company_employee.go
- internal/logic/company/company_team.go
- 增加需要删除团队管理员|队长是组长的条件  employeeId = 0, teamId !=0
> pref: 团队相关方法优化及版本更新

- co_interface/co_interface.go
- go.mod
- go.sum
- internal/logic/company/company.go
- internal/logic/company/company_employee.go
- internal/logic/company/company_team.go
1. 需要移除团队成员记录
2. 假如是团队队长|组长|负责人，相关的团队Team记录需要修改TeamCaptain和TeamOwner字段的值
> feat: 删除员工的移除对应的有关团队记录 

- go.mod
- go.sum
- internal/logic/company/company.go
- internal/logic/company/company_employee.go
- internal/logic/company/company_team.go
fix: 修复员工查询数据模型的调用 Bug
fix: 修复团队查询数据模型调用错误Bug
> fix: 修复团队查询数据模型调用错误Bug 

- example/router/router.go
- 应该使用的是co_v1包写下面的接口，这样才会有接口分类
> fix: 路由注册路径错误 Bug

- api/co_company_api/employee.go
- api/co_company_api/my.go
- api/co_v1/employee.go
- api/co_v1/my.go
- co_controller/internal/employee.go
- co_controller/internal/my.go
- co_interface/i_controller/employee.go
- co_interface/i_controller/my.go
- co_router/router.go
- example/controller/employee.go
- example/controller/my.go
- example/router/router.go
- 接口名称修改： setEmployeeAvatar --> setAvatar
- 接口位置修改：员工 --> 我的
> pref: 将设置员工头像迁移到my模块下面

- api/co_company_api/employee.go
- api/co_company_api/my.go
- api/co_v1/employee.go
- api/co_v1/my.go
- co_controller/internal/employee.go
- co_controller/internal/my.go
- co_interface/i_controller/employee.go
- co_interface/i_controller/my.go
- co_interface/service_interface.go
- co_router/router.go
- example/controller/employee.go
- example/controller/my.go
- example/router/router.go
- internal/logic/company/company_employee.go
- 接口名称修改： setEmployeeMobile --> setMobile
- 接口位置修改：员工 --> 我的
> pref: 将设置员工手机号迁移到my模块下面

- internal/logic/company/company_employee.go
- 支持扩展过滤字段  teamId, employeeId, inviteUserId, unionMainId
> pref 查询员工接口增加扩展过滤字段支持

- example/i18n/company/zh-CN.yaml
- i18n/company/zh-CN.yaml
- internal/logic/company/my.go
> fix: 查询我的团队信息的时候对错误信息进行包装

- internal/logic/company/company_employee.go
- 优化为公共模块的： 
- makeMore和makeBuilder方法进行附加数据的获取
- 因为With对缓存不友好
> pref: 去掉orm的with操作，

- co_controller/internal/my.go
- 因为是直接调用别的层的方法，所以直接写上关于他们的订阅定义就好。
> feat: 我的接口控制层添加相关附加信息订阅

- internal/logic/company/company.go
- internal/logic/company/company_employee.go
> fix: 修复查看公司更多信息时未做主体校验 Bug

- example/internal/boot/boot.go
#	example/internal/boot/boot.go
> pref: 规范接口定义

- co_model/co_dao/internal/fd_invoice.go
- co_model/co_do/fd_invoice.go
- co_model/co_entity/fd_invoice.go
- co_model/fd_invoice.go
- go.mod
- go.sum
- internal/logic/financial/fd_invoice.go
- 审核字段回复拼写错误 `replay` -> `reply`
> fix: 修复审核回复字段拼写错误

- Makefile
- co_consts/co_const.go
- co_interface/service_interface.go
- co_model/co_dao/internal/fd_account.go
- co_model/co_dao/internal/fd_account_bill.go
- co_model/co_do/fd_account.go
- co_model/co_do/fd_account_bill.go
- co_model/co_entity/fd_account.go
- co_model/co_entity/fd_account_bill.go
- co_model/fd_account.go
- co_model/fd_account_bill.go
- example/i18n/company/zh-CN.yaml
- go.mod
- go.sum
- i18n/company/zh-CN.yaml
- internal/logic/company/company.go
- internal/logic/company/company_employee.go
- internal/logic/company/company_team.go
- internal/logic/financial/fd_account.go
- internal/logic/financial/fd_account_bill.go
- manifest/config/config.yaml
- 优化company逻辑,创建公司默认的系统财务账号
- 修复跨主体判断条件Bug
- 优化财务部分逻辑方法
> pref: 优化company逻辑,创建公司默认的系统财务账号

- api/co_company_api/my.go
- api/co_v1/my.go
- co_controller/internal/my.go
- co_interface/i_controller/financial.go
- co_interface/i_controller/my.go
- co_interface/service_interface.go
- co_model/fd_account.go
- co_model/my.go
- co_permission/internal/financial/permission.go
- co_router/router.go
- example/controller/my.go
- example/router/router.go
- internal/logic/company/my.go
- internal/logic/financial/fd_account.go
我的财务：
- // GetAccountBills 我的账单|列表
- // GetAccounts 获取我的财务账号|列表
- // GetBankCards 获取我的银行卡｜列表
- // GetInvoices 获取我的发票抬头|列表
- // UpdateAccount  修改我的财务账号
> feat: 添加我的财务模块实现

- co_controller/internal/company.go
- co_controller/internal/employee.go
- co_controller/internal/financial.go
- co_controller/internal/team.go
- co_interface/i_controller/employee.go
- co_interface/i_controller/financial.go
- co_interface/i_controller/team.go
- co_interface/service_interface.go
- co_module/modules.go
- internal/logic/company/company.go
- internal/logic/company/company_employee.go
- internal/logic/company/company_team.go
- internal/logic/company/my.go
- internal/logic/financial/fd_account_bill.go
- 去掉dao *co_dao.XDao对象的指针调用
- 实现自定义company组合，支持一对多，自由组合
> pref: 主体、团队、员工的关系解耦

- co_model/company.go
- internal/logic/company/company.go
- 在公司模型中新增LogoId和StarLevel字段
- 在公司逻辑中实现Logo的保存功能，确保上传路径和文件处理的正确性
> feat: 添加公司模型的LogoId和StarLevel字段，并在公司逻辑中处理Logo保存逻辑
